' Developer Express Code Central Example:
' How to colorize map contours loaded from Shapefiles using the Choropleth colorizer
' 
' This example demonstrates how to paint each map contour in a specific color
' depending on GDP data from Shapefiles (Countries.dbf, Countries.shp).
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E4691
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18047
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace Colorizer.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As Colorizer.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Colorizer.Properties.Settings())), Colorizer.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return Colorizer.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
